name: task_zing_m_v_p
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  blurhash_dart: 1.2.1
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.0
  cloud_firestore_platform_interface: ^7.0.0
  cloud_firestore_web: ^5.0.0
  collection: 1.19.1
  csslib: ^1.0.2
  csv: 6.0.0
  data_table_2: ^2.5.18
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  file_picker: ^10.2.1
  firebase_auth: ^6.0.0
  firebase_auth_platform_interface: ^8.0.0
  firebase_auth_web: ^6.0.0
  firebase_core: ^4.0.0
  firebase_core_platform_interface: ^6.0.0
  firebase_core_web: ^3.0.0
  firebase_performance: ^0.11.0
  firebase_performance_platform_interface: ^0.1.5+11
  firebase_performance_web: ^0.1.7+17
  firebase_storage: ^13.0.0
  firebase_storage_platform_interface: ^5.2.11
  firebase_storage_web: ^3.10.18
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_plugin_android_lifecycle: ^2.0.26
  flutter_rating_bar: 4.0.1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_macos: ^4.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  flutter_secure_storage_web: ^2.0.0
  flutter_secure_storage_windows: ^4.0.0
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.9.0
  from_css_color: 2.0.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  go_router: ^15.1.2
  google_fonts: ^6.3.0
  google_maps_flutter: ^2.10.1
  google_sign_in: ^6.2.2
  google_sign_in_android: ^6.1.35
  google_sign_in_ios: ^5.9.0
  google_sign_in_platform_interface: ^2.5.0
  google_sign_in_web: ^0.12.4+4
  html: ^0.15.6
  image: ^4.5.4
  image_picker: 1.1.2
  image_picker_android: ^0.8.12+21
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+2
  image_picker_linux: ^0.2.1+2
  image_picker_macos: ^0.2.1+2
  image_picker_platform_interface: ^2.10.1
  image_picker_windows: 0.2.1+1
  intl: 0.20.2
  json_path: ^0.7.6
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  plugin_platform_interface: 2.1.8
  provider: ^6.1.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.7
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4+6
  stream_transform: ^2.1.1
  synchronized: ^3.3.0+3
  table_calendar: ^3.1.3
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: ^3.1.4
  video_player: ^2.9.5
  video_player_android: ^2.7.16
  video_player_avfoundation: ^2.7.1
  video_player_platform_interface: ^6.3.0
  video_player_web: ^2.3.5
  widget_to_marker: 1.0.6
  flutter_stripe: ^11.5.0

  stripe_platform_interface: ^11.5.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3

  crypto: any
dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

